#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITBudgetApp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ITBudgetApp")]
	public partial class ITBudgetAppDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ITBudgetAppDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ITBudgetAppConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ITBudgetAppDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ITBudgetAppDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ITBudgetAppDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ITBudgetAppDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_Tracker_Update")]
		public int usp_Tracker_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PreviousYearBudgeted", DbType="Decimal(10,2)")] System.Nullable<decimal> previousYearBudgeted, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CurrentYearBudgeted", DbType="Decimal(10,2)")] System.Nullable<decimal> currentYearBudgeted, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Actual", DbType="Decimal(10,2)")] System.Nullable<decimal> actual, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsNet", DbType="Int")] System.Nullable<int> isNet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), previousYearBudgeted, currentYearBudgeted, actual, id, isNet);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_Tracker_Get")]
		public ISingleResult<usp_Tracker_GetResult> usp_Tracker_Get([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Month", DbType="Int")] System.Nullable<int> month, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Year", DbType="Int")] System.Nullable<int> year, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CostId", DbType="Int")] System.Nullable<int> costId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompanyId", DbType="Int")] System.Nullable<int> companyId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), month, year, costId, companyId);
			return ((ISingleResult<usp_Tracker_GetResult>)(result.ReturnValue));
		}
	}
	
	public partial class usp_Tracker_GetResult
	{
		
		private int _Id;
		
		private System.Nullable<int> _Month;
		
		private string _MonthName;
		
		private System.Nullable<int> _Year;
		
		private int _CostId;
		
		private string _CostName;
		
		private int _CostCentreId;
		
		private string _CostCentre;
		
		private int _CompanyId;
		
		private string _Company;
		
		private System.Nullable<decimal> _PreviousYearBudgetedNet;
		
		private System.Nullable<decimal> _PreviousYearBudgetedGross;
		
		private System.Nullable<decimal> _CurrentYearBudgetedNet;
		
		private System.Nullable<decimal> _CurrentYearBudgetedGross;
		
		private System.Nullable<decimal> _ActualNet;
		
		private System.Nullable<decimal> _ActualGross;
		
		private System.Nullable<decimal> _DifferenceNet;
		
		private System.Nullable<decimal> _DifferenceGross;
		
		public usp_Tracker_GetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="Int")]
		public System.Nullable<int> Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this._Month = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonthName", DbType="NVarChar(30)")]
		public string MonthName
		{
			get
			{
				return this._MonthName;
			}
			set
			{
				if ((this._MonthName != value))
				{
					this._MonthName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int")]
		public System.Nullable<int> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this._Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostId", DbType="Int NOT NULL")]
		public int CostId
		{
			get
			{
				return this._CostId;
			}
			set
			{
				if ((this._CostId != value))
				{
					this._CostId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostName", DbType="VarChar(200)")]
		public string CostName
		{
			get
			{
				return this._CostName;
			}
			set
			{
				if ((this._CostName != value))
				{
					this._CostName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostCentreId", DbType="Int NOT NULL")]
		public int CostCentreId
		{
			get
			{
				return this._CostCentreId;
			}
			set
			{
				if ((this._CostCentreId != value))
				{
					this._CostCentreId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostCentre", DbType="VarChar(200)")]
		public string CostCentre
		{
			get
			{
				return this._CostCentre;
			}
			set
			{
				if ((this._CostCentre != value))
				{
					this._CostCentre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyId", DbType="Int NOT NULL")]
		public int CompanyId
		{
			get
			{
				return this._CompanyId;
			}
			set
			{
				if ((this._CompanyId != value))
				{
					this._CompanyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="VarChar(100)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this._Company = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreviousYearBudgetedNet", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> PreviousYearBudgetedNet
		{
			get
			{
				return this._PreviousYearBudgetedNet;
			}
			set
			{
				if ((this._PreviousYearBudgetedNet != value))
				{
					this._PreviousYearBudgetedNet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreviousYearBudgetedGross", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> PreviousYearBudgetedGross
		{
			get
			{
				return this._PreviousYearBudgetedGross;
			}
			set
			{
				if ((this._PreviousYearBudgetedGross != value))
				{
					this._PreviousYearBudgetedGross = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentYearBudgetedNet", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> CurrentYearBudgetedNet
		{
			get
			{
				return this._CurrentYearBudgetedNet;
			}
			set
			{
				if ((this._CurrentYearBudgetedNet != value))
				{
					this._CurrentYearBudgetedNet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentYearBudgetedGross", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> CurrentYearBudgetedGross
		{
			get
			{
				return this._CurrentYearBudgetedGross;
			}
			set
			{
				if ((this._CurrentYearBudgetedGross != value))
				{
					this._CurrentYearBudgetedGross = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActualNet", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> ActualNet
		{
			get
			{
				return this._ActualNet;
			}
			set
			{
				if ((this._ActualNet != value))
				{
					this._ActualNet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActualGross", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> ActualGross
		{
			get
			{
				return this._ActualGross;
			}
			set
			{
				if ((this._ActualGross != value))
				{
					this._ActualGross = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DifferenceNet", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> DifferenceNet
		{
			get
			{
				return this._DifferenceNet;
			}
			set
			{
				if ((this._DifferenceNet != value))
				{
					this._DifferenceNet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DifferenceGross", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> DifferenceGross
		{
			get
			{
				return this._DifferenceGross;
			}
			set
			{
				if ((this._DifferenceGross != value))
				{
					this._DifferenceGross = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
